import RollDigitalizer from "../RollDigitalizer";
import Scope from "../scope/Scope";
export default class TransitionRoll implements RollDigitalizer {
    readonly mode: number;
    private transition;
    private scope;
    private easingStyle;
    constructor(scope: Scope, style: string);
    private getScrollElement;
    private getScrollStyle;
    private getZonePosition;
    isFreeScroll(): boolean;
    isHScroll(): boolean;
    isVScroll(): boolean;
    isHPassthrough(): boolean;
    isVPassthrough(): boolean;
    isTransition(): boolean;
    isResilient(): boolean;
    isOnRush(): boolean;
    isPeak(): boolean;
    isClickable(): boolean;
    isTapable(): boolean;
    getDirectionLockThreshold(): number;
    getMaxScroll(): ScrollKit.Point;
    getPosition(): ScrollKit.Point;
    getSize(): ScrollKit.Point;
    getDeceleration(): number;
    getComputedPosition(): ScrollKit.Point;
    stop(): void;
    resetPosition(): void;
    getState(): number;
    setAnimation(style: string): void;
    setState(state: number): void;
    translate(x: number, y: number): void;
    scrollTo(x: number, y: number, time: number): void;
}
